#!/usr/bin/python
from . import siswa
from . import propinsi
from . import pekerjaan
from . import berkas_pendaftaran
from . import kelas
from . import ustadz_wali
from . import kelas_paralel
from . import matpel
from . import aspek_matpel
from . import kesehatan
from . import pelanggaran
from . import tindakan_hukuman
from . import perijinan
from . import keuangan_siswa
from . import jns_pembayaran
from . import pembayaran_siswa
from . import status_hafalan
from . import tahsin_siswa
from . import prestasi_siswa
from . import jns_prestasi
from . import uang_saku_siswa
from . import ustadz_pengajar
from . import tahfidz_siswa