#-*- coding: utf-8 -*-

{
	"name": "Cdn pesantren",
	"version": "1.0", 
	"depends": [
		'base',
		'hr'
	],
	"author": "Akhmad D. Sembiring [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Cdn pesantren module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/ir.model.access.csv",
		"view/menu.xml",
		"view/siswa.xml",
		# "view/propinsi.xml",
		"view/pekerjaan.xml",
		"view/berkas_pendaftaran.xml",
		#"view/kelas.xml",
		# "view/ustadz_wali.xml",
		#"view/kelas_paralel.xml",
		#"view/matpel.xml",
		#"view/aspek_matpel.xml",
		"view/kesehatan.xml",
		"view/pelanggaran.xml",
		"view/tindakan_hukuman.xml",
		"view/perijinan.xml",
		"view/keuangan_siswa.xml",
		"view/jns_pembayaran.xml",
		"view/pembayaran_siswa.xml",
		"view/status_hafalan.xml",
		"view/tahsin_siswa.xml",
		"view/prestasi_siswa.xml",
		"view/jns_prestasi.xml",
		"view/uang_saku_siswa.xml",
		# "view/ustadz_pengajar.xml",
		"view/tahfidz_siswa.xml",
		"report/siswa.xml",
		"report/propinsi.xml",
		"report/pekerjaan.xml",
		"report/berkas_pendaftaran.xml",
		"report/kelas.xml",
		"report/ustadz_wali.xml",
		"report/kelas_paralel.xml",
		"report/matpel.xml",
		"report/aspek_matpel.xml",
		"report/kesehatan.xml",
		"report/pelanggaran.xml",
		"report/tindakan_hukuman.xml",
		"report/perijinan.xml",
		"report/keuangan_siswa.xml",
		"report/jns_pembayaran.xml",
		"report/pembayaran_siswa.xml",
		"report/status_hafalan.xml",
		"report/tahsin_siswa.xml",
		"report/prestasi_siswa.xml",
		"report/jns_prestasi.xml",
		"report/uang_saku_siswa.xml",
		"report/ustadz_pengajar.xml",
		"report/tahfidz_siswa.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}